/**
 * Texture.h
 * Authors: Sheldon Taylor, Jiju Poovvancheri
 *
 * Implementation of OpenGL-based texture generation.
 */

#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <string>
#include "Noise.h"
#include "Mesh.h"
#include "Shader.h"

#include <memory>
#include <OpenGP/types.h>
#include <glm/glm/glm.hpp>

#include <GL/glew.h>
#include <GLFW/glfw3.h>

#include <stb_image/stb_image.h>
#include <OpenGP/GL/Texture.h>

#ifndef _TEXTURE_H_
#define _TEXTURE_H_


class Texture {
public:
    Texture();
    ~Texture();

    // Reads in noise texture from file (generated by program)
    int readNoiseTexture(GLuint *tex);
    int generateNoiseTexture(GLuint *tex);

    // Reads in skybox textures from file
    int readSkyboxTexture(unsigned int i, std::string filename);
    int generateSkyboxTexture(int i, std::string filename);

    // Reads in skybox textures from file
    int readTerrainTexture(int i, std::string filename);
    int generateTerrainTexture(int i, std::string filename);
};

#endif
