FIND_PATH( ASSIMP_INCLUDE_DIRS
        /local/include)

FIND_LIBRARY( ASSIMP_LIBRARIES NAMES assimp PATHS
        /usr/local/lib)

SET(ASSIMP_FOUND "NO")
IF(ASSIMP_LIBRARIES AND ASSIMP_INCLUDE_DIRS)
    SET(ASSIMP_FOUND "YES")
    message(STATUS "Found ASSIMP: ${ASSIMP_LIBRARIES}")
ENDIF(ASSIMP_LIBRARIES AND ASSIMP_INCLUDE_DIRS)
